production/urls.py
from django.urls import path
from . import views

app_name = 'production'

urlpatterns = [
    path('accounts/login/', views.custom_login, name='custom_login'),
    path('accounts/logout/', views.custom_logout, name='custom_logout'),

    path('', views.index, name='main'),

    path('dictionary/', views.dictionary, name='dictionary'),
    path('dictionary_last_id/<str:dict_type>', views.dictionary_last_id, name='dictionary_last_id'),
    path('dict_update/<str:dict_type>', views.dictionary_update, name='dictionary_update'),
    path('dict_delete/<str:dict_type>/<int:id_no>', views.dictionary_delete, name='dictionary_delete'),
    path(
        'json_dict_next_20/<str:dict_type>/<int:id_no>/<str:order>/<str:search_string>/<int:show_deleted>/<int:unclosed>',
        views.dictionary_json, name='dictionary_json'),
    path('dictionary_json_filter/<str:dict_type>/<str:filter_dictionary>/<int:filter_dictionary_id>',
         views.dictionary_json_filter, name='dictionary_json_filter'),

    path('tech_dictionary/', views.tech_dictionary, name='tech_dictionary'),

    path('production_request/', views.production_request, name='production_request'),
    path('production_request_close/<int:request_id>', views.production_request_close, name='production_request_close'),

    path('production_start/', views.production_start, name='production_start'),
    path('production_stop/', views.production_stop, name='production_stop'),
    path('production_report/', views.production_report, name='production_report'),

    path('production/', views.production, name='production'),
    path('production_list/<int:first_record>/<str:order>/<int:unclosed>/<str:search_string>', views.production_list,
         name='production_list'),
    path('production_acceptance/', views.production_acceptance, name='production_acceptance'),

    path('quality_report/', views.quality_report, name='quality_report'),
    path('quality_list/<str:date_start>/<str:date_end>', views.quality_list, name='quality_list'),
    path('defects_left/<int:quality_report_id>', views.rest_defects_list, name='rest_defects_list'),
    path('quality_report_update/', views.quality_report_update, name='quality_report_update'),

    path('production_admin/', views.production_admin, name='production_admin'),
    path('imm_free/', views.imm_free_list, name='imm_free'),

]

productionUnit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin_production/', admin.site.urls),
    path('production/', include('production.urls')),
]

production/models/account_info.py
from django.db import models

from production.models import Equipment


class AccountInfoEquipment(models.Model):
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    year_production = models.IntegerField(null=True, blank=True)
    date_received = models.DateField(null=True, blank=True)
    date_start = models.DateField(null=True, blank=True)
    start_cost = models.IntegerField(null=True, blank=True)
    amortization = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True)

production/models/color_models.py
from django.db import models


class ColorScheme(models.Model):
    """ color scheme IV, Grant, Eco """
    scheme_name = models.CharField(max_length=13, unique=True)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return self.scheme_name

    def __str__(self):
        return str(self.scheme_name)

    class Meta:
        ordering = ['scheme_name']

    @staticmethod
    def order_default():
        return ['scheme_name']


class Color(models.Model):
    """ code - (07)
        colr_name - name
        pantone - pantone color
        color_code - HEX"""
    code = models.CharField(max_length=10)
    pantone = models.CharField(max_length=20, default='')
    color_name = models.CharField(max_length=60)
    color_code = models.CharField(max_length=7)
    color_scheme = models.ForeignKey(ColorScheme, models.SET_NULL, null=True)
    standard = models.BooleanField(default=True)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return f"{self.code} {self.color_name}"

    def __str__(self):
        return f"{self.code} {self.color_name}"

    class Meta:
        ordering = ['color_scheme', 'code']

    @staticmethod
    def order_default():
        return ['color_scheme', 'code']

production/models/country.py
from django.db import models


class Country(models.Model):
    name = models.CharField(max_length=40, default='РФ', unique=True)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    @staticmethod
    def order_default():
        return ['name']

production/models/defects.py
from django.db import models


class Defects(models.Model):
    name = models.CharField(max_length=120, unique=True)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    @staticmethod
    def order_default():
        return ['name']


class DefectEvent(models.Model):
    name = models.CharField(max_length=120, unique=True)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    @staticmethod
    def order_default():
        return ['name']

production/models/detail_models.py
from django.db import models
from production.models import Goods, RecipeColorScheme


class DetailName(models.Model):
    name = models.CharField(max_length=40, unique=True)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return self.name

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']

    @staticmethod
    def order_default():
        return ['name']


class DetailInGoods(models.Model):
    goods = models.ForeignKey(Goods, models.SET_NULL, null=True)
    detail_name = models.ForeignKey(DetailName, models.SET_NULL, null=True, blank=True)
    position = models.SmallIntegerField(default=1)
    recipe_color_scheme = models.ForeignKey(RecipeColorScheme, on_delete=models.SET_NULL, null=True, blank=True,
                                            default=None)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return f"{self.goods.article}.{self.position} {self.detail_name.name}"

    def __str__(self):
        return f"{self.goods.article}.{self.position} {self.detail_name.name}"

    class Meta:
        ordering = ['goods__article', 'position']

    @staticmethod
    def order_default():
        return ['goods__article', 'position']

production/models/detail_producing_parameters.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models

from production.models import DetailBaseData, Color, IMM


class DetailProducingParameters(models.Model):
    imm = models.ForeignKey(IMM, models.SET_NULL, null=True, blank=True)
    color = models.ForeignKey(Color, models.SET_NULL, null=True, blank=True)
    detail_base_data = models.ForeignKey(DetailBaseData, models.SET_NULL, null=True, blank=True)
    deleted = models.BooleanField(default=False)

    class Meta:
        ordering = ['imm', 'detail_base_data__detail_in_goods']

    @staticmethod
    def order_default():
        return ['imm', 'detail_base_data__detail_in_goods']


class MoldTemperature(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)
    core_temperature = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)
    cavity_temperature = models.DecimalField(max_digits=5, decimal_places=1, null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class ImmZonesTemperature(models.Model):
    mold_temperature = models.ForeignKey(MoldTemperature, on_delete=models.CASCADE)
    zone_no = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(6)])
    zone_temperature = models.DecimalField(max_digits=6, decimal_places=2, null=True, blank=True)

    class Meta:
        ordering = ['zone_no']

    @staticmethod
    def order_default():
        return ['zone_no']


class HotRunnerZonesTemperature(models.Model):
    mold_temperature = models.ForeignKey(MoldTemperature, on_delete=models.CASCADE)
    zone_no = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(32)])
    zone_temperature = models.DecimalField(max_digits=6, decimal_places=2)

    class Meta:
        ordering = ['zone_no']

    @staticmethod
    def order_default():
        return ['zone_no']


class MaterialLoading(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)
    position_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    pressure_bar = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    speed_mm_sec = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    back_pressure_bar = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    decompression_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class MaterialInjection(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)
    pressure_bar = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    injection_time_sec = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    position_before_switch_mm = models.DecimalField(max_digits=4, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class MaterialInjectionPosition(models.Model):
    material_injection = models.ForeignKey(MaterialInjection, on_delete=models.CASCADE, null=True, blank=True)
    position_no = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(6)])
    position_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    injection_speed_mm_sec = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['position_no']

    @staticmethod
    def order_default():
        return ['position_no']


class MoldHolding(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)
    position_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    speed_percent = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    holding_time_sec = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    start_pressure_bar = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    end_pressure_bar = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class ClampingUnitParameters(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)
    clamping_force_kN = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class ClampingUnitMoving(models.Model):
    clamping_unit_parameters = models.ForeignKey(ClampingUnitParameters, on_delete=models.CASCADE, null=True,
                                                 blank=True)
    position_no = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    position_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    opening = models.BooleanField(default=False)

    class Meta:
        ordering = ['opening', 'position_no']

    @staticmethod
    def order_default():
        return ['opening', 'position_no']


class MoldProtectionParameters(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)
    mold_protection_start_mm = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    mold_protection_end_mm = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    mold_protection_force_kN = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    mold_protection_time_sec = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class HydraulicCoresParameters(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class HydraulicCoresMoving(models.Model):
    hydraulic_core_parameters = models.ForeignKey(HydraulicCoresParameters, on_delete=models.CASCADE, null=True,
                                                  blank=True)
    forward = models.BooleanField(default=True)
    core_no = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(5)])
    pressure_bar = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    position_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    speed_mm_sec = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)
    time_sec = models.DecimalField(max_digits=6, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['core_no', 'forward']

    @staticmethod
    def order_default():
        return ['core_no', 'forward']


class EjectorParameters(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)
    pressure_bar = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    speed_mm_sec = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    timeout_forward_sec = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    timeout_backward_sec = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    stroke_quantity = models.IntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(3)], null=True)
    position_forward_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)
    position_backward_mm = models.DecimalField(max_digits=5, decimal_places=1, default=0.0, null=True, blank=True)

    class Meta:
        ordering = ['detail_producing_parameters']

    @staticmethod
    def order_default():
        return ['detail_producing_parameters']


class CoolingParameters(models.Model):
    detail_producing_parameters = models.OneToOneField(DetailProducingParameters, on_delete=models.CASCADE, null=True)
    imm_page = models.IntegerField(null=True, blank=True)

production/models/detail_tech_data.py
from django.db import models
from production.models import DetailInGoods, ProductionReport, MoldInsert


class DetailBaseData(models.Model):
    detail_in_goods = models.ForeignKey(DetailInGoods, on_delete=models.CASCADE)
    mold_insert = models.ForeignKey(MoldInsert, models.SET_NULL, null=True)
    weight_g = models.DecimalField(default=0, decimal_places=3, max_digits=9)
    cycle_time_seconds = models.IntegerField(default=0)
    date_create = models.DateTimeField(auto_now_add=True)
    deleted = models.BooleanField(default=False)

    def __repr__(self):
        return self.weight_g

    def __str__(self):
        return str(self.weight_g)

    class Meta:
        ordering = ['detail_in_goods', '-date_create']

    @staticmethod
    def order_default():
        return ['detail_in_goods', '-date_create']


class DetailActualData(DetailBaseData):
    production = models.ForeignKey(ProductionReport, on_delete=models.CASCADE)
    cavities_quantity_working = models.IntegerField()

templates/dropdown_code.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

{#var 1#}
<div class="dropdown" onclick="openDropdown(this);">
    <input name="id" type="text" class="dropdown__hidden" hidden>
    <ul class="dropdown__content" id="itemDropdown">
        <div class="dropdown__input-block">
            <input type="text" class="dropdown__input"
                   placeholder="Поиск.." onkeyup="filterList(this);"
                   value="{{ money_arguments.0.description }}"
                   data-value="{{ money_arguments.0.description }}">
            <i class="fa fa-solid fa-angle-down"></i>
        </div>
        {% for argument in money_arguments %}
            <li data-value="{{ argument.code }}" class="visible"
                onclick="event.stopPropagation(); selectFromList(this);">{{ argument.description }} </li>
        {% endfor %}
    </ul>
</div>
{#var2#}
<div class="dropdown report_dropdown" onclick="openDropdown(this);">
    <input name="id" type="text" class="dropdown__hidden" hidden id="report-select-1"
           value="{{ cst_reports.0.code }}">
    <div class="dropdown__input-block">
        <input type="text" class="dropdown__input"
               placeholder="Поиск.." onchange="changeArgumentList(this)"
               value="{{ cst_reports.0.description }}"
               data-value="{{ cst_reports.0.description }}" readonly>
        <i class="fa fa-solid fa-angle-down"></i>
    </div>
    <ul class="dropdown__content">
        {% for report in cst_reports %}
            <li data-value="{{ report.code }}"
                onclick="event.stopPropagation(); selectFromList(this);">{{ report.description }} </li>
        {% endfor %}
    </ul>
</div>

{#old report#}
<div class="report-block" id="report-10001">
    <div class="report-header">
        <p class="report-heading">Отчет по товарам</p>
    </div>
    <div class="report-block-content">

        <label for="report-10001" class="top-label">тип отчета</label>
        <select class="form-select" id="report-select-10001" onchange="changeArgumentList(this)">
            {% for report in goods_reports %}
                <option value="{{ report.code }}">{{ report.description }}</option>
            {% endfor %}
        </select> <label for="period-10001" class="top-label">период</label>
        <select class="form-select" id="period-select-10001">
            {% for period in periods %}
                <option value="{{ period.value }}">{{ period.label }}</option>
            {% endfor %}
        </select>
        <div class="date-row">
            <div>c&nbsp;<input type="date" class="form-input report__form-input"></div>
            <div>&nbsp;до&nbsp;<input type="date" class="form-input report__form-input"></div>
        </div>
        <label for="parameter-select-10001" class="top-label">показатель</label>
        <select class="form-select" id="parameter-select-10001">
            {% for argument in money_arguments %}
                <option value="{{ argument.code }}">{{ argument.description }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="button-block report_button-block">
        <button type="button" class="btn btn-close" onclick="reportRemove(this)">Уничтожить отчет
        </button>
        <button type="button" class="btn btn-save" onclick="buildReport(this)">Создать отчет</button>
    </div>
</div>


<script src="{% static 'marketing_report/js/main.js' %}"></script>

</body>
</html>

templates/header.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Производство</title>
    <link rel="icon" type="image/x-icon" href="{% static 'production/icon/plant.svg' %}">

    <script src="{% static 'production/js/dist/login.bundle.js' %}" defer type="module"></script>
{#    <script src="{% static 'production/js/login.js' %}" defer type="module"></script>#}
    <script src="https://kit.fontawesome.com/e2a5b405b2.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'production/css/style.css' %}">

    <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet'>

</head>
<body>
<input class="form-input" id="user-group" value="{{ user_groups }}" hidden>
<header class="header">
    <div class="container">
        <menu class="menu">
            <div class="menu__mobile menu__item"><i class="fa fa-solid fa-bars"></i></div>
            <div class="menu__left">
                <a href="http://10.0.1.17/wcenter/"
                   class="menu__item"><span class="mobile__hide"><i class="fa fa-solid fa-arrows-to-circle"></i></span>
                    <span class="mobile__show">&nbsp;Центр</span>
                </a>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'production:main' %}"
                       class="menu__item {% if navi == 'main' %}active{% endif %}">Главная</a>
                    <a href=#
                       class="menu__item {% if navi == 'production_data' %}active{% endif %}">Производство</a>
                    <a href="{% url 'production:production_request' %}"
                       class="menu__item menu__item_badge  mobile__hide {% if navi == 'request' %}active{% endif %}">Заявки</a>
                    <a href="{% url 'production:production' %}"
                       class="menu__item menu__item_badge {% if navi == 'production' %}active{% endif %}">Приемка</a>
                    <a href="{% url 'production:quality_report' %}"
                       class="menu__item mobile__hide {% if navi == 'quality' %}active{% endif %}">Отчет ОТК</a>
                    <a href="{% url 'production:dictionary' %}"
                       class="menu__item mobile__hide {% if navi == 'dictionary' %}active{% endif %}">Настройки</a>
                    <a href="{% url 'production:tech_dictionary' %}"
                       class="menu__item mobile__hide {% if navi == 'tech_dictionary' %}active{% endif %}">Технология</a>
                {% else %}
                    <div class="menu__item">Производство V4.4.2&nbsp;<strong>Авторизуйтесь</strong></div>
                {% endif %}
                {% if admin_state %}
                    <a href="{% url 'production:production_admin' %}"
                       class="menu__item {% if navi == 'admin' %}active{% endif %}">Админ</a>
                {% endif %}
            </div>
            <nav class="menu__right">
                {% if request.user.is_authenticated %}
                    <div class="menu__item active" id="logout-button">{{ request.user.first_name }}&nbsp;{{ request.user.last_name }}<i
                            class="fa fa-solid fa-arrow-right-from-bracket"></i></div>
                    <div class="menu__item" id="login-button" hidden> вход</div>
                {% else %}
                    <div class="menu__item active" id="login-button"><i
                            class="fa fa-solid fa-arrow-right-to-bracket"></i>&nbsp;вход
                    </div>
                    <div class="menu__item" hidden> выход</div>
                {% endif %}
            <div class="menu__item">ver 4.4.3</div>
            </nav>
        </menu>
    </div>
</header>

{% if request.user.is_authenticated %}
    {% block content %}
    {% endblock %}
{% else %}
    <div class="container">
        <div class="auth-needed">
            <svg xmlns="http://www.w3.org/2000/svg" height="50vh" viewBox="0 0 512 512" fill="#536D79">
                <!--! Font Awesome Free 6.4.2 by @fontawesome
             - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
                <path d="M99.5 144.8L178.7 224l96 96 92.5 92.5C335.9 434.9 297.5 448 256 448C150 448 64 362 64 256c0-41.5 13.1-79.9
    35.5-111.2zM333.3 288l-32-32H384v32H333.3zm32 32H400c8.8 0 16-7.2 16-16V240c0-8.8-7.2-16-16-16H269.3L144.8
    99.5C176.1 77.1 214.5 64 256 64c106 0 192 86 192 192c0 41.5-13.1 79.9-35.5 111.2L365.3 320zM256 512A256 256 0 1 0
    256 0a256 256 0 1 0 0 512zM272 96c-8.8 0-16 7.2-16 16c0 26.5 21.5 48 48 48h32c8.8 0 16 7.2 16 16s7.2 16 16 16s16-7.2
    16-16c0-26.5-21.5-48-48-48H304c-8.8 0-16-7.2-16-16s-7.2-16-16-16zM229.5 320l-96-96H112c-8.8 0-16 7.2-16 16v64c0 8.8
    7.2 16 16 16H229.5z"/>
            </svg>
        </div>
    </div>
{% endif %}

<input class="badges" hidden value="{{ badge_count }}">

<!-- Модальное окно для входа и выхода -->
<div id="authModal" class="login">
    <div class="login__content">
        <!-- Форма для входа -->
        <form method="post" id="login-form" action="{% url 'production:custom_login' %}">
            {% csrf_token %}
            <div class="login__header">
                <p class="active">Вход</p>
                <span class="login__close">&times;</span>
            </div>

            <input type="text" name="username" placeholder="Имя пользователя" required class="login__input">
            <input type="password" name="password" placeholder="Пароль" required class="login__input">
            <div class="login__buttons">
                <button type="submit" class="btn btn-save">Войти</button>
            </div>
        </form>

        <!-- Форма для выхода -->
        <form method="post" id="logout-form" action="{% url 'production:custom_logout' %}">
            {% csrf_token %}
            <div class="login__header">
                <p class="active">Выход</p>
                <span class="login__close">&times;</span>
            </div>
            <p class="login__text">Вы уверены, что хотите выйти?</p>
            <div class="login__buttons">
                <button type="submit" class="btn btn-save">Выйти</button>
            </div>
        </form>
    </div>
</div>

</body>
</html>